"""Build Stage 5U next-stage decision records."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from libreprimus.cuda_candidate_batch_abi.export import read_record_set, write_record_set, write_report
from libreprimus.cuda_candidate_batch_abi.models import (
    ABI_GAP_CLOSURE_PATH,
    COMMON_FLAGS,
    NEXT_STAGE_DECISION_JSON,
    NEXT_STAGE_DECISION_PATH,
    NEXT_STAGE_REASON,
    NEXT_STAGE_TITLE,
    OUTPUT_DIR,
)


def build_next_stage_decision(
    *,
    gap_closure: Path = ABI_GAP_CLOSURE_PATH,
    next_stage_decision_out: Path = NEXT_STAGE_DECISION_PATH,
    out_dir: Path = OUTPUT_DIR,
) -> list[dict[str, Any]]:
    """Select the next bounded stage after contract-only ABI definition."""

    closures = read_record_set(gap_closure)
    implementation_pending_count = sum(1 for record in closures if record.get("implementation_pending"))
    rows = [
        (
            "stage5v_native_candidate_batch_abi_reference_adapter",
            "selected",
            True,
            "Codex",
            NEXT_STAGE_TITLE,
            NEXT_STAGE_REASON,
            "low",
            False,
            True,
            False,
            True,
            False,
            False,
            ["native_reference_implementation_pending"],
        ),
        (
            "stage5v_affine_mod29_cuda_contract",
            "deferred_until_native_abi_conformance",
            False,
            "Codex",
            "Stage 5V - affine/reverse mod-29 CUDA contract preparation",
            "Affine work still needs native ABI conformance and family-specific contract confirmation.",
            "medium",
            False,
            False,
            False,
            False,
            True,
            False,
            ["native_reference_implementation_pending", "family_specific_contract_pending"],
        ),
        (
            "stage5v_prime_minus_one_stream_contract",
            "deferred_until_stream_conformance",
            False,
            "Codex",
            "Stage 5V - prime-minus-one stream CUDA contract and native parity preparation",
            "Prime-stream remains high value but stream schedules need no-GPU conformance fixtures first.",
            "medium",
            False,
            False,
            False,
            False,
            True,
            False,
            ["native_reference_implementation_pending", "stream_schedule_conformance_pending"],
        ),
        (
            "stage5v_vigenere_key_schedule_contract",
            "deferred_until_key_schedule_conformance",
            False,
            "Codex",
            "Stage 5V - explicit-key Vigenere CUDA contract and key-schedule parity preparation",
            "Explicit-key Vigenere needs key-schedule conformance fixtures before CUDA contract work.",
            "medium",
            False,
            False,
            False,
            False,
            True,
            False,
            ["native_reference_implementation_pending", "key_schedule_conformance_pending"],
        ),
        (
            "stage5v_reverse_rotated_contract",
            "deferred_until_family_contract",
            False,
            "Codex",
            "Stage 5V - reverse and rotated reverse mod-29 CUDA contract preparation",
            "Reverse-family formulas are simple but original-transform semantics still require family-specific contract records.",
            "low",
            False,
            False,
            False,
            False,
            True,
            False,
            ["family_specific_contract_pending"],
        ),
        (
            "stage5v_topk_contract",
            "deferred_until_score_vector_conformance",
            False,
            "Codex",
            "Stage 5V - top-k reducer contract preparation",
            "Top-k should wait until score-vector conformance exists and score direction metadata is explicit.",
            "medium",
            False,
            False,
            True,
            False,
            False,
            True,
            ["score_vector_conformance_pending", "topk_conformance_pending"],
        ),
        (
            "stage5v_benchmark_planning",
            "deferred_no_execution",
            False,
            "Codex",
            "Stage 5V - benchmark planning refresh",
            "Benchmark planning can cite Stage 5U, but execution remains blocked until native/CUDA parity scope exists.",
            "medium",
            True,
            False,
            False,
            False,
            False,
            False,
            ["native_reference_implementation_pending", "cuda_contract_pending"],
        ),
        (
            "stage5v_pause_cuda_return_to_research",
            "not_selected",
            False,
            "Deep Research",
            "Deep Research - CUDA ABI review",
            "Stage 5U can define the ABI without another research pause; Deep Research is not selected next.",
            "low",
            False,
            False,
            False,
            False,
            False,
            False,
            ["not_needed_after_stage5u_contracts"],
        ),
        (
            "stage6_website_expansion",
            "not_selected",
            False,
            "Codex",
            "Stage 6 - website expansion",
            "Website expansion remains deferred and unrelated to the Candidate Batch ABI contract.",
            "low",
            False,
            False,
            False,
            False,
            False,
            False,
            ["deferred_to_stage6"],
        ),
    ]
    records = [
        {
            "record_type": "cuda_next_stage_decision_record",
            "next_stage_decision_id": f"stage5u-next-stage-{index:02d}",
            "option_id": option_id,
            "status": status,
            "selected": selected,
            "recommended_prompt_type": prompt_type,
            "recommended_stage_title": title,
            "rationale": rationale,
            "risk_level": risk_level,
            "cuda_execution_allowed": False,
            "cuda_source_changes_allowed": False,
            "benchmark_execution_allowed": False,
            "benchmark_planning_allowed": benchmark_planning,
            "unsolved_page_cuda_allowed": False,
            "generated_body_publication_allowed": False,
            "method_status_upgrade_allowed": False,
            "requires_stage5u_contracts": True,
            "requires_native_reference_implementation": requires_native,
            "requires_family_specific_contract": requires_family_contract,
            "requires_score_vector_contract": requires_score_vector,
            "requires_topk_contract": requires_topk,
            "deep_research_recommended_next": prompt_type == "Deep Research" and selected,
            "implementation_pending_count": implementation_pending_count,
            "blockers": blockers,
            **COMMON_FLAGS,
        }
        for index, (
            option_id,
            status,
            selected,
            prompt_type,
            title,
            rationale,
            risk_level,
            benchmark_planning,
            requires_native,
            requires_score_vector,
            requires_family_contract,
            _deep_research_marker,
            requires_topk,
            blockers,
        ) in enumerate(rows)
    ]
    for record in records:
        if record["option_id"] == "stage5v_pause_cuda_return_to_research":
            record["deep_research_recommended_next"] = False
        if record["option_id"] == "stage5v_native_candidate_batch_abi_reference_adapter":
            record["requires_family_specific_contract"] = False
    write_record_set(next_stage_decision_out, records)
    write_report(out_dir, NEXT_STAGE_DECISION_JSON, {"records": records})
    return records
